package labels

import (
	"fmt"

	"github.com/ing-bank/golibs/pkg/slices"
	"github.com/ing-bank/golibs/pkg/store"
	"k8s.io/apimachinery/pkg/labels"
)

// GenerateLabelSelector creates a label selector that matches the given immutable labels selectors and the provided
// additional selector.
func GenerateLabelSelector(immutable map[string]string, additional string) (labels.Selector, error) {
	additionalSelector, err := labels.Parse(additional)
	if err != nil {
		return nil, err
	}

	if len(immutable) == 0 {
		return additionalSelector, nil
	}

	baseSelector := labels.SelectorFromSet(immutable)
	baseReqs, selectable := baseSelector.Requirements()
	if !selectable {
		return nil, fmt.Errorf("base selector is not selectable")
	}

	additionalReqs, selectable := additionalSelector.Requirements()
	if !selectable {
		return nil, fmt.Errorf("additional selector is not selectable")
	}

	for _, aReq := range additionalReqs {
		for _, bReq := range baseReqs {
			if aReq.Key() == bReq.Key() {
				return nil, fmt.Errorf("cannot override additional label selector over immutable key '%s'", aReq.Key())
				// We could check for equality instead of outright rejecting, but it seems more transparent for the user
				// if we just reject any attempt to additional an immutable label selector. Keep it simple.
				// For posterity, checking equality can be achieved like so:
				// aReq.Operator() == bReq.Operator() && len(slices.SymmetricDifference(aReq.Values().List(), bReq.Values().List())) == 0
			}
		}
	}

	requirements := append(baseReqs, additionalReqs...)
	sel := labels.NewSelector().Add(requirements...)
	return sel, nil
}

func EnrichWithLabelSelectorOption(immutable map[string]string, opts *[]store.Option) error {
	additional, _ := MatchLabelSelector(opts)
	selector, err := GenerateLabelSelector(immutable, additional)
	if err != nil {
		return err
	}
	*opts = append(*opts, WithLabelSelector(selector.String()))
	return nil
}

// EnrichWithLabelsOption updates the options to set the provided immutable labels
// To be used as a utility function by store Backends
func EnrichWithLabelsOption(immutable map[string]string, opts *[]store.Option) error {
	customLabels, _ := MatchLabels(opts)
	for _, customLabel := range customLabels {
		if _, ok := immutable[customLabel]; ok {
			return fmt.Errorf("label %s is immutable and cannot be set as a custom label", customLabel)
		}
	}
	*opts = append(*opts, WithLabels(slices.MergeMap(customLabels, immutable)))
	return nil
}

// BuildLabels generates a set of labels given
// - immutable labels that must be set for any object and cannot be overridden
// - object specific labels that are generated by the provided enricher. Cannot be overridden by custom labels
// - additional custom labels provided by WithLabels store option
func BuildLabels[V any](
	obj V,
	immutable map[string]string,
	enricher func(obj V) (map[string]string, error),
	opts *[]store.Option,
) (
	map[string]string, error,
) {
	customLabels, found := MatchLabels(opts)
	if !found {
		customLabels = make(map[string]string)
	}
	objLabels := map[string]string{}
	if enricher != nil {
		var err error
		objLabels, err = enricher(obj)
		if err != nil {
			return nil, err
		}
	}

	// Return error when ImmutableLabels are overridden by customLabels or objLabels
	for k := range immutable {
		if _, ok := customLabels[k]; ok {
			return nil, fmt.Errorf("label %s is immutable", k)
		}
		if _, ok := objLabels[k]; ok {
			return nil, fmt.Errorf("label %s is immutable", k)
		}
	}

	return slices.MergeMap(objLabels, customLabels, immutable), nil
}
