package http

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/ing-bank/golibs/pkg/http/tripperware"
	"github.com/ing-bank/golibs/pkg/tlsclient"
	"github.com/ing-bank/golibs/pkg/tlsutils"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

type ExamplePayload struct {
	Data  string `json:"data"`
	Value int    `json:"value"`
}

func ExampleMetrics() {
	// Create new HTTP client with Metrics tripperware
	c, _ := NewClient(WithTripperware(tripperware.Metrics(false)))

	// Setup Metrics server
	ts := httptest.NewServer(promhttp.Handler())
	defer ts.Close()
	time.Sleep(1 * time.Second) // Give metrics server some time

	// Generate some metrics via the Metrics tripperware of the HTTP client
	ctx := context.Background()
	_ = c.Get(ctx, ts.URL+"/metrics")

	// First "scrape" has no meaningful metrics, all zero
	// But now the Metrics middleware will have generated metrics

	// Fetch generated Metrics
	resp := c.Get(ctx, ts.URL+"/metrics")
	if !resp.IsOK() {
		panic(fmt.Sprintf("failed to get metrics: %s", resp.Error()))
	}

	for line := range strings.SplitSeq(string(resp.Raw), "\n") {
		if strings.Contains(line, "golibs_http_client_request_count_total") {
			//fmt.Println("client_http_request_count_total{host=\"localhost:*\",method=\"GET\"} 1")
			if strings.Contains(line, "golibs_http_client_request_count_total{") {
				line = strings.ReplaceAll(line, ts.Listener.Addr().String(), "localhost:2112")
				fmt.Println(line)
				break
			}
		}
	}

	// Output:
	// golibs_http_client_request_count_total{host="localhost:2112",method="GET"} 1
}

func ExampleNewClient() {
	// This example showcases most of the options that the client can take
	client, err := NewClient(
		WithTripperware(tripperware.DefaultTripperware),
		WithNewTraceTransport(
			// InsecureSkipVerify(),
			// WithTLS(cert, key, CAs...)
		),
		WithRequestOptions(
			WithHeaders(map[string]string{"foo": "bar"}),
			// http.WithBasicAuth(usernameFromEnv, passwordFromEnv)
		),
	)
	if err != nil {
		panic(err)
	}

	// Setup testing HTTP server
	type ExamplePayload struct {
		Data  string `json:"data"`
		Value int    `json:"value"`
	}
	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		raw, _ := json.Marshal(&ExamplePayload{"Hello world", 1})
		_, _ = w.Write(raw)
	}))
	defer ts.Close()
	ctx := context.Background()

	response := &ExamplePayload{}
	if resp := client.Get(ctx, ts.URL).Parse(response); !resp.IsOK() {
		panic(resp.Error())
	}
	fmt.Println(response) // Logging stdout from tripperware is ignored during tests

	// Output:
	// &{Hello world 1}
}

func ExampleClient_Get() {
	// Setup fake server that returns JSON ExamplePayload
	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "text/plain")
		raw, _ := json.Marshal(&ExamplePayload{"Hello world", 1})
		_, _ = w.Write(raw)
	}))
	defer ts.Close()

	// Create new HTTP client
	ctx := context.Background()
	client, _ := NewClient()

	// Call server and parse payload
	response := &ExamplePayload{}
	resp := client.Get(ctx, ts.URL).Parse(response)
	if !resp.IsOK() {
		panic(resp.Error())
	}
	// client.Get returns a Response type.
	// on Response, we can safely call Parse. If there was an error in the http request this is a no-op.
	// resp.IsOK lets us know whether there were any transport, http or parsing errors, is shorthand for
	// resp.Error() != nil

	fmt.Printf("Header Content-Type: %v\n", resp.Headers.Get("Content-Type"))
	fmt.Println(response)
	// Output:
	// Header Content-Type: text/plain
	// &{Hello world 1}
}

func ExampleWithTLS() {
	ts := httptest.NewTLSServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		raw, _ := json.Marshal(&ExamplePayload{"Hello world", 1})
		_, _ = w.Write(raw)
	}))
	defer ts.Close()

	// Create new HTTP client
	// Normally you would use WithNewTransport(WithTLS(...)) to load certificates stored on disk
	// In this case we hijack the certificates generated by httptest
	transport := ts.Client().Transport.(*http.Transport)
	client, _ := NewClient(WithTransport(transport))
	ctx := context.Background()

	// Call server and parse payload
	response := &ExamplePayload{}
	if resp := client.Get(ctx, ts.URL).Parse(response); !resp.IsOK() {
		panic(resp.Error())
	}

	fmt.Println(response)
	// Output:
	// &{Hello world 1}
}

func ExampleNewForConfig() {
	// Create a private temp directory for this example.
	dir, err := os.MkdirTemp(os.TempDir(), "go-http-*")
	if err != nil {
		panic(err)
	}
	defer os.RemoveAll(dir)

	certPath := filepath.Join(dir, "cert.pem")
	keyPath := filepath.Join(dir, "key.pem")

	if err := os.WriteFile(certPath, rsaCertPEM, 0o600); err != nil {
		panic(err)
	}
	if err := os.WriteFile(keyPath, rsaKeyPEM, 0o600); err != nil {
		panic(err)
	}

	cfg := &Config{
		TLS: tlsclient.Config{
			Config: tlsutils.Config{
				Cert: certPath,
				Key:  keyPath,
			},
			InsecureSkipVerify: true,
		},
		DefaultHeaders: map[string]string{
			"Authorization": "Bearer token",
			"X-Custom":      "value",
		},
	}

	client, err := NewForConfig(cfg)
	if err != nil {
		panic(err)
	}

	ts := httptest.NewTLSServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		raw, _ := json.Marshal(&ExamplePayload{"Hello world", 1})
		_, _ = w.Write(raw)
	}))
	defer ts.Close()

	// Call server and parse payload
	response := &ExamplePayload{}
	if resp := client.Get(context.Background(), ts.URL).Parse(response); !resp.IsOK() {
		panic(resp.Error())
	}

	fmt.Println(response)
	// Output:
	// &{Hello world 1}
}
